package com.example.ui.theme

object Localization {
    fun translate(key: String, language: String): String {
        val isArabic = language == "Arabic" || language == "العربية"
        return if (isArabic) {
            arabicTranslations[key] ?: englishTranslations[key] ?: key
        } else {
            englishTranslations[key] ?: key
        }
    }

    private val englishTranslations = mapOf(
        "home" to "Home",
        "welcome" to "Assalamu Alaykum,",
        "quick_services" to "Quick Services",
        "daily_verse" to "Daily Quran Verse",
        "read_tafsir" to "Read Tafsir",
        "continue_reading" to "Continue Reading",
        "quran_listening" to "Quran Listening",
        "daily_hadith" to "Daily Hadith",
        "quran" to "Quran",
        "prayer_times" to "Prayer Times",
        "qibla" to "Qibla",
        "azkar" to "Azkar",
        "audio_quran" to "Audio Quran",
        "khatmah" to "Khatmah",
        "quiz" to "Quiz",
        "duas" to "Duas",
        "tasbeeh" to "Tasbeeh",
        "settings" to "Settings",
        "save" to "Save",
        "edit_name" to "Edit Name",
        "settings_options" to "Settings & Options",
        "dark_mode" to "Obsidian Emerald Dark Mode",
        "quran_font_style" to "Quranic Arabic Font Style",
        "quran_text_size" to "Quran Reading Text Size",
        "prayer_calc_method" to "Prayer Calculation Method",
        "app_language" to "Application Language",
        "choose_language" to "Choose Language",
        "back" to "Back",
        "compass" to "Qibla Compass",
        "align_phone" to "Align your phone facing the Qibla arrow to find the Holy Kaaba.",
        "qibla_angle" to "Qibla Angle",
        "daily_azkar" to "Daily Azkar",
        "repeat" to "Repeat",
        "share" to "Share",
        "favorite" to "Favorite",
        "khatmah_planner" to "Khatmah Planner",
        "pages_read" to "Pages Read",
        "remaining" to "Remaining",
        "daily_target" to "Daily Target",
        "add_pages" to "+5 Pages",
        "add_juz" to "+1 Juz' (20p)",
        "unlocked" to "Unlocked",
        "locked" to "Locked",
        "bronze_badge" to "Bronze Scholar",
        "silver_badge" to "Silver Huffaz",
        "gold_badge" to "Golden Noor",
        "start_khatmah" to "Start Khatmah",
        "reach_50" to "Reach 50%",
        "complete_quran" to "Complete Quran",
        "create_new_khatmah" to "Create New Khatmah Plan",
        "title" to "Plan Title",
        "finish_goal" to "Finish Goal (Days)",
        "daily_reading_target" to "Daily Reading Target (Minutes)",
        "initialize_khatmah" to "Initialize Plan",
        "praise_allah" to "Praise Allah",
        "memorization_quiz" to "Memorization Quiz",
        "streak" to "Streak",
        "verify_answer" to "Verify Answer",
        "next_question" to "Next Question",
        "islamic_duas" to "Islamic Duas",
        "holy_quran" to "Holy Quran",
        "search_surah" to "Search Surah or English meaning...",
        "surahs" to "Surahs",
        "bookmarks" to "Bookmarks",
        "no_bookmarks" to "No Bookmarked verses yet.",
        "reciting" to "Reciting",
        "word_meanings" to "Word Meanings (Tap to collapse)",
        "tafsir_title" to "Tafsir Al-Muntakhab",
        "play_audio" to "Play Audio",
        "stop" to "Stop",
        "copied" to "Copied verse!",
        "morning" to "Morning",
        "evening" to "Evening",
        "sleep" to "Sleep",
        "travel" to "Travel",
        "next_prayer" to "Next",
        "utc_live" to "UTC LIVE",
        "ai_scholar" to "Noor Al-Quran AI",
        "chat_placeholder" to "Ask about Quran meanings, Tafsir, or Islamic guidance...",
        "ai_thinking" to "Noor AI is reflecting...",
        "clear_chat" to "Clear Chat",
        "select_reciter" to "Select Reciter",
        "change_reciter" to "Change Voice",
        "reciter_mishary" to "Mishary Rashid Alafasy",
        "reciter_abdul_basit" to "Abdul Basit Abdus Samad",
        "reciter_minshawi" to "Mohamed Siddiq El-Minshawi",
        "reciter_shuraim" to "Saud Al-Shuraim",
        "reciter_sudais" to "Abdul Rahman Al-Sudais",
        "reciter_yasser_al_dosari" to "Yasser Al-Dosari",
        "reciter_islam_sobhi" to "Islam Sobhi",
        "daylight_saving_time" to "Daylight Saving Time (+1h)",
        "prayer_approaching_alert" to "Prayer Approaching Alert (15m)",
        "tasbeeh_sound" to "Tasbih Click Sound",
        "tasbeeh_vibration" to "Tasbih Vibration",
        "download" to "Download",
        "downloaded" to "Downloaded",
        "downloading" to "Downloading",
        "delete_audio" to "Delete Offline Audio"
    )

    private val arabicTranslations = mapOf(
        "home" to "الرئيسية",
        "welcome" to "السلام عليكم،",
        "quick_services" to "الخدمات السريعة",
        "daily_verse" to "الآية اليومية",
        "read_tafsir" to "قراءة التفسير",
        "continue_reading" to "مواصلة القراءة",
        "quran_listening" to "الاستماع للقرآن",
        "daily_hadith" to "الحديث اليومي",
        "quran" to "القرآن الكريم",
        "prayer_times" to "مواقيت الصلاة",
        "qibla" to "القبلة",
        "azkar" to "الأذكار",
        "audio_quran" to "المصحف الصوتي",
        "khatmah" to "الختمة",
        "quiz" to "اختبار الحفظ",
        "duas" to "الأدعية",
        "tasbeeh" to "التسبيح",
        "settings" to "الإعدادات",
        "save" to "حفظ",
        "edit_name" to "تعديل الاسم",
        "settings_options" to "الإعدادات والخيارات",
        "dark_mode" to "الوضع المظلم الزمردي",
        "quran_font_style" to "خط الرسم العثماني",
        "quran_text_size" to "حجم خط القراءة",
        "prayer_calc_method" to "طريقة حساب الصلاة",
        "app_language" to "لغة التطبيق",
        "choose_language" to "اختر اللغة",
        "back" to "رجوع",
        "compass" to "بوصلة القبلة",
        "align_phone" to "ضع الهاتف في اتجاه سهم القبلة لتحديد الكعبة المشرفة.",
        "qibla_angle" to "زاوية القبلة",
        "daily_azkar" to "الأذكار اليومية",
        "repeat" to "التكرار",
        "share" to "مشاركة",
        "favorite" to "المفضلة",
        "khatmah_planner" to "مخطط الختمة",
        "pages_read" to "الصفحات المقروءة",
        "remaining" to "المتبقي",
        "daily_target" to "الهدف اليومي",
        "add_pages" to "+5 صفحات",
        "add_juz" to "+1 جزء (20 صفحة)",
        "unlocked" to "تم فتحها",
        "locked" to "مغلقة",
        "bronze_badge" to "الباحث البرونزي",
        "silver_badge" to "الحافظ الفضي",
        "gold_badge" to "النور الذهبي",
        "start_khatmah" to "بدء الختمة",
        "reach_50" to "الوصول لـ 50%",
        "complete_quran" to "ختم القرآن",
        "create_new_khatmah" to "إنشاء خطة ختمة جديدة",
        "title" to "عنوان الخطة",
        "finish_goal" to "هدف الانتهاء (أيام)",
        "daily_reading_target" to "الهدف اليومي للقراءة (دقائق)",
        "initialize_khatmah" to "بدء خطة الختمة",
        "praise_allah" to "سبّح الله",
        "memorization_quiz" to "اختبار الحفظ",
        "streak" to "المتتالية",
        "verify_answer" to "تحقق من الإجابة",
        "next_question" to "السؤال التالي",
        "islamic_duas" to "الأدعية الإسلامية",
        "holy_quran" to "القرآن الكريم",
        "search_surah" to "ابحث عن سورة أو معنى...",
        "surahs" to "السور",
        "bookmarks" to "العلامات المرجعية",
        "no_bookmarks" to "لا توجد علامات مرجعية بعد.",
        "reciting" to "القارئ",
        "word_meanings" to "معاني الكلمات (اضغط للإغلاق)",
        "tafsir_title" to "تفسير المنتخب",
        "play_audio" to "تشغيل الصوت",
        "stop" to "إيقاف",
        "copied" to "تم نسخ الآية!",
        "morning" to "الصباح",
        "evening" to "المساء",
        "sleep" to "النوم",
        "travel" to "السفر",
        "next_prayer" to "الصلاة القادمة",
        "utc_live" to "مباشر UTC",
        "ai_scholar" to "نور القرآن AI",
        "chat_placeholder" to "اسأل عن معاني الآيات، التفسير، أو الأحكام الشرعية...",
        "ai_thinking" to "نور يفكر الآن...",
        "clear_chat" to "مسح المحادثة",
        "select_reciter" to "اختر القارئ",
        "change_reciter" to "تغيير القارئ",
        "reciter_mishary" to "مشاري راشد العفاسي",
        "reciter_abdul_basit" to "عبد الباسط عبد الصمد",
        "reciter_minshawi" to "محمد صديق المنشاوي",
        "reciter_shuraim" to "سعود الشريم",
        "reciter_sudais" to "عبد الرحمن السديس",
        "reciter_yasser_al_dosari" to "ياسر الدوسري",
        "reciter_islam_sobhi" to "إسلام صبحي",
        "daylight_saving_time" to "التوقيت الصيفي (+١ ساعة)",
        "prayer_approaching_alert" to "تنبيه اقتراب الصلاة (قبلها بـ ١٥ د)",
        "tasbeeh_sound" to "صوت كليك التسبيح",
        "tasbeeh_vibration" to "اهتزاز السبحة",
        "download" to "تحميل",
        "downloaded" to "تم التحميل",
        "downloading" to "جاري التحميل",
        "delete_audio" to "حذف الصوت المحمل"
    )
}
