package com.example.ui.theme

object Localization {
    fun translate(key: String, language: String): String {
        return when (language) {
            "Arabic", "العربية" -> arabicTranslations[key] ?: englishTranslations[key] ?: key
            "German", "Deutsch", "الألمانية" -> germanTranslations[key] ?: englishTranslations[key] ?: key
            "Hindi", "हिन्दी", "الهندية" -> hindiTranslations[key] ?: englishTranslations[key] ?: key
            "Chinese", "中文", "الصينية" -> chineseTranslations[key] ?: englishTranslations[key] ?: key
            "Spanish", "Español", "الإسبانية" -> spanishTranslations[key] ?: englishTranslations[key] ?: key
            "French", "Français", "الفرنسية" -> frenchTranslations[key] ?: englishTranslations[key] ?: key
            else -> englishTranslations[key] ?: key
        }
    }

    private val englishTranslations = mapOf(
        "home" to "Home",
        "welcome" to "Assalamu Alaykum,",
        "quick_services" to "Quick Services",
        "daily_verse" to "Daily Quran Verse",
        "read_tafsir" to "Read Tafsir",
        "continue_reading" to "Continue Reading",
        "quran_listening" to "Quran Listening",
        "daily_hadith" to "Daily Hadith",
        "quran" to "Quran",
        "prayer_times" to "Prayer Times",
        "qibla" to "Qibla",
        "azkar" to "Azkar",
        "audio_quran" to "Audio Quran",
        "khatmah" to "Khatmah",
        "quiz" to "Quiz",
        "duas" to "Duas",
        "tasbeeh" to "Tasbeeh",
        "zakat" to "Zakat Calculator",
        "settings" to "Settings",
        "save" to "Save",
        "edit_name" to "Edit Name",
        "settings_options" to "Settings & Options",
        "dark_mode" to "Obsidian Emerald Dark Mode",
        "quran_font_style" to "Quranic Arabic Font Style",
        "quran_text_size" to "Quran Reading Text Size",
        "prayer_calc_method" to "Prayer Calculation Method",
        "app_language" to "Application Language",
        "choose_language" to "Choose Language",
        "back" to "Back",
        "compass" to "Qibla Compass",
        "align_phone" to "Align your phone facing the Qibla arrow to find the Holy Kaaba.",
        "qibla_angle" to "Qibla Angle",
        "daily_azkar" to "Daily Azkar",
        "repeat" to "Repeat",
        "share" to "Share",
        "favorite" to "Favorite",
        "khatmah_planner" to "Khatmah Planner",
        "pages_read" to "Pages Read",
        "remaining" to "Remaining",
        "daily_target" to "Daily Target",
        "add_pages" to "+5 Pages",
        "add_juz" to "+1 Juz' (20p)",
        "unlocked" to "Unlocked",
        "locked" to "Locked",
        "bronze_badge" to "Bronze Scholar",
        "silver_badge" to "Silver Huffaz",
        "gold_badge" to "Golden Noor",
        "start_khatmah" to "Start Khatmah",
        "reach_50" to "Reach 50%",
        "complete_quran" to "Complete Quran",
        "create_new_khatmah" to "Create New Khatmah Plan",
        "title" to "Plan Title",
        "finish_goal" to "Finish Goal (Days)",
        "daily_reading_target" to "Daily Reading Target (Minutes)",
        "initialize_khatmah" to "Initialize Plan",
        "praise_allah" to "Praise Allah",
        "memorization_quiz" to "Memorization Quiz",
        "streak" to "Streak",
        "verify_answer" to "Verify Answer",
        "next_question" to "Next Question",
        "islamic_duas" to "Islamic Duas",
        "holy_quran" to "Holy Quran",
        "search_surah" to "Search Surah or English meaning...",
        "surahs" to "Surahs",
        "bookmarks" to "Bookmarks",
        "no_bookmarks" to "No Bookmarked verses yet.",
        "reciting" to "Reciting",
        "word_meanings" to "Word Meanings (Tap to collapse)",
        "tafsir_title" to "Tafsir Al-Muntakhab",
        "play_audio" to "Play Audio",
        "stop" to "Stop",
        "copied" to "Copied verse!",
        "morning" to "Morning",
        "evening" to "Evening",
        "sleep" to "Sleep",
        "travel" to "Travel",
        "next_prayer" to "Next",
        "utc_live" to "UTC LIVE",
        "ai_scholar" to "Noor Al-Quran AI",
        "chat_placeholder" to "Ask about Quran meanings, Tafsir, or Islamic guidance...",
        "ai_thinking" to "Noor AI is reflecting...",
        "clear_chat" to "Clear Chat",
        "select_reciter" to "Select Reciter",
        "change_reciter" to "Change Voice",
        "reciter_mishary" to "Mishary Rashid Alafasy",
        "reciter_abdul_basit" to "Abdul Basit Abdus Samad",
        "reciter_minshawi" to "Mohamed Siddiq El-Minshawi",
        "reciter_shuraim" to "Saud Al-Shuraim",
        "reciter_sudais" to "Abdul Rahman Al-Sudais",
        "reciter_yasser_al_dosari" to "Yasser Al-Dosari",
        "reciter_islam_sobhi" to "Islam Sobhi",
        "daylight_saving_time" to "Daylight Saving Time (+1h)",
        "prayer_approaching_alert" to "Prayer Approaching Alert (15m)",
        "tasbeeh_sound" to "Tasbih Click Sound",
        "tasbeeh_vibration" to "Tasbih Vibration",
        "download" to "Download",
        "downloaded" to "Downloaded",
        "downloading" to "Downloading",
        "delete_audio" to "Delete Offline Audio",
        "live_radio" to "Live Radio",
        "live_radio_subtitle" to "Direct Live Quran Broadcasts",
        "choose_radio" to "Choose Live Broadcast",
        "radio_cairo" to "Quran Cairo Radio",
        "radio_saudi" to "Quran Saudi Radio",
        "radio_alafasy" to "Mishary Alafasy Live",
        "radio_basit" to "Abdul Basit Mojawwad Live",
        "radio_minshawi" to "Mohamed Siddiq El-Minshawi Live",
        "radio_yasser" to "Yasser Al-Dosari Live",
        "radio_maher" to "Maher Al-Muaiqly Live",
        "radio_ajmy" to "Ahmad Al-Ajmy Live",
        "radio_ghamdi" to "Saad Al-Ghamdi Live",
        "radio_shuraim" to "Saud Al-Shuraim Live",
        "radio_sudais" to "Abdul Rahman Al-Sudais Live",
        "live_broadcasting" to "LIVE BROADCAST",
        "now_playing_radio" to "Now Playing Live Radio",
        "downloads" to "Downloads",
        "downloads_subtitle" to "Downloaded Quran & Adhan audio",
        "all_downloads" to "My Downloads",
        "quran_downloads" to "Quran Audio",
        "adhan_downloads" to "Adhan Audio",
        "no_downloads" to "No downloaded audio files yet",
        "battery_card_title" to "Background Work Stability",
        "battery_card_desc" to "Exempt the app from battery restriction for accurate and on-time Adhan alerts",
        "battery_card_btn" to "Exempt from Optimization"
    )

    private val arabicTranslations = mapOf(
        "home" to "الرئيسية",
        "welcome" to "السلام عليكم،",
        "quick_services" to "الخدمات السريعة",
        "daily_verse" to "الآية اليومية",
        "read_tafsir" to "قراءة التفسير",
        "continue_reading" to "مواصلة القراءة",
        "quran_listening" to "الاستماع للقرآن",
        "daily_hadith" to "الحديث اليومي",
        "quran" to "القرآن الكريم",
        "prayer_times" to "مواقيت الصلاة",
        "qibla" to "القبلة",
        "azkar" to "الأذكار",
        "audio_quran" to "المصحف الصوتي",
        "khatmah" to "الختمة",
        "quiz" to "اختبار الحفظ",
        "duas" to "الأدعية",
        "tasbeeh" to "التسبيح",
        "zakat" to "حاسبة الزكاة",
        "settings" to "الإعدادات",
        "save" to "حفظ",
        "edit_name" to "تعديل الاسم",
        "settings_options" to "الإعدادات والخيارات",
        "dark_mode" to "الوضع المظلم الزمردي",
        "quran_font_style" to "خط الرسم العثماني",
        "quran_text_size" to "حجم خط القراءة",
        "prayer_calc_method" to "طريقة حساب الصلاة",
        "app_language" to "لغة التطبيق",
        "choose_language" to "اختر اللغة",
        "back" to "رجوع",
        "compass" to "بوصلة القبلة",
        "align_phone" to "ضع الهاتف في اتجاه سهم القبلة لتحديد الكعبة المشرفة.",
        "qibla_angle" to "زاوية القبلة",
        "daily_azkar" to "الأذكار اليومية",
        "repeat" to "التكرار",
        "share" to "مشاركة",
        "favorite" to "المفضلة",
        "khatmah_planner" to "مخطط الختمة",
        "pages_read" to "الصفحات المقروءة",
        "remaining" to "المتبقي",
        "daily_target" to "الهدف اليومي",
        "add_pages" to "+5 صفحات",
        "add_juz" to "+1 جزء (20 صفحة)",
        "unlocked" to "تم فتحها",
        "locked" to "مغلقة",
        "bronze_badge" to "الباحث البرونزي",
        "silver_badge" to "الحافظ الفضي",
        "gold_badge" to "النور الذهبي",
        "start_khatmah" to "بدء الختمة",
        "reach_50" to "الوصول لـ 50%",
        "complete_quran" to "ختم القرآن",
        "create_new_khatmah" to "إنشاء خطة ختمة جديدة",
        "title" to "عنوان الخطة",
        "finish_goal" to "هدف الانتهاء (أيام)",
        "daily_reading_target" to "الهدف اليومي للقراءة (دقائق)",
        "initialize_khatmah" to "بدء خطة الختمة",
        "praise_allah" to "سبّح الله",
        "memorization_quiz" to "اختبار الحفظ",
        "streak" to "المتتالية",
        "verify_answer" to "تحقق من الإجابة",
        "next_question" to "السؤال التالي",
        "islamic_duas" to "الأدعية الإسلامية",
        "holy_quran" to "القرآن الكريم",
        "search_surah" to "ابحث عن سورة أو معنى...",
        "surahs" to "السور",
        "bookmarks" to "العلامات المرجعية",
        "no_bookmarks" to "لا توجد علامات مرجعية بعد.",
        "reciting" to "القارئ",
        "word_meanings" to "معاني الكلمات (اضغط للإغلاق)",
        "tafsir_title" to "تفسير المنتخب",
        "play_audio" to "تشغيل الصوت",
        "stop" to "إيقاف",
        "copied" to "تم نسخ الآية!",
        "morning" to "الصباح",
        "evening" to "المساء",
        "sleep" to "النوم",
        "travel" to "السفر",
        "next_prayer" to "الصلاة القادمة",
        "utc_live" to "مباشر UTC",
        "ai_scholar" to "نور القرآن AI",
        "chat_placeholder" to "اسأل عن معاني الآيات، التفسير، أو الأحكام الشرعية...",
        "ai_thinking" to "نور يفكر الآن...",
        "clear_chat" to "مسح المحادثة",
        "select_reciter" to "اختر القارئ",
        "change_reciter" to "تغيير القارئ",
        "reciter_mishary" to "مشاري راشد العفاسي",
        "reciter_abdul_basit" to "عبد الباسط عبد الصمد",
        "reciter_minshawi" to "محمد صديق المنشاوي",
        "reciter_shuraim" to "سعود الشريم",
        "reciter_sudais" to "عبد الرحمن السديس",
        "reciter_yasser_al_dosari" to "ياسر الدوسري",
        "reciter_islam_sobhi" to "إسلام صبحي",
        "daylight_saving_time" to "التوقيت الصيفي (+١ ساعة)",
        "prayer_approaching_alert" to "تنبيه اقتراب الصلاة (قبلها بـ ١٥ د)",
        "tasbeeh_sound" to "صوت كليك التسبيح",
        "tasbeeh_vibration" to "اهتزاز السبحة",
        "download" to "تحميل",
        "downloaded" to "تم التحميل",
        "downloading" to "جاري التحميل",
        "delete_audio" to "حذف الصوت المحمل",
        "live_radio" to "البث المباشر",
        "live_radio_subtitle" to "إذاعات القرآن الكريم المباشرة",
        "choose_radio" to "اختر إذاعة البث المباشر",
        "radio_cairo" to "إذاعة القرآن الكريم من القاهرة",
        "radio_saudi" to "إذاعة القرآن الكريم من السعودية",
        "radio_alafasy" to "إذاعة الشيخ مشاري العفاسي",
        "radio_basit" to "إذاعة الشيخ عبد الباسط عبد الصمد",
        "radio_minshawi" to "إذاعة الشيخ محمد صديق المنشاوي",
        "radio_yasser" to "إذاعة الشيخ ياسر الدوسري",
        "radio_maher" to "إذاعة الشيخ ماهر المعيقلي",
        "radio_ajmy" to "إذاعة الشيخ أحمد العجمي",
        "radio_ghamdi" to "إذاعة الشيخ سعد الغامدي",
        "radio_shuraim" to "إذاعة الشيخ سعود الشريم",
        "radio_sudais" to "إذاعة الشيخ عبد الرحمن السديس",
        "live_broadcasting" to "بث مباشر",
        "now_playing_radio" to "المستمع الآن للبث المباشر",
        "downloads" to "التحميلات",
        "downloads_subtitle" to "ملفات القرآن الكريم والأذان المحملة",
        "all_downloads" to "ملفاتي المحملة",
        "quran_downloads" to "القرآن الكريم",
        "adhan_downloads" to "الأذان وصوت المؤذن",
        "no_downloads" to "لا توجد ملفات صوتية محملة بعد",
        "battery_card_title" to "استقرار عمل الأذان في الخلفية",
        "battery_card_desc" to "يُرجى السماح للتطبيق بالعمل في الخلفية دون قيود البطارية لضمان تنبيهات أذان دقيقة ودون تأخير",
        "battery_card_btn" to "استثناء من قيود البطارية"
    )

    private val germanTranslations = mapOf(
        "home" to "Startseite",
        "welcome" to "Assalamu Alaykum,",
        "quick_services" to "Schnelldienste",
        "daily_verse" to "Täglicher Koranvers",
        "read_tafsir" to "Tafsir lesen",
        "continue_reading" to "Weiterlesen",
        "quran_listening" to "Koran hören",
        "daily_hadith" to "Täglicher Hadith",
        "quran" to "Koran",
        "prayer_times" to "Gebetszeiten",
        "qibla" to "Qibla",
        "azkar" to "Azkar",
        "audio_quran" to "Audio-Koran",
        "khatmah" to "Khatmah",
        "quiz" to "Quiz",
        "duas" to "Bittgebete (Duas)",
        "tasbeeh" to "Tasbih",
        "settings" to "Einstellungen",
        "save" to "Speichern",
        "edit_name" to "Name bearbeiten",
        "settings_options" to "Einstellungen & Optionen",
        "dark_mode" to "Obsidian Smaragd Dunkelmodus",
        "quran_font_style" to "Koranische arabische Schriftart",
        "quran_text_size" to "Textgröße beim Koran lesen",
        "prayer_calc_method" to "Berechnungsmethode für Gebete",
        "app_language" to "App-Sprache",
        "choose_language" to "Sprache wählen",
        "back" to "Zurück",
        "compass" to "Qibla-Kompass",
        "align_phone" to "Richten Sie Ihr Telefon nach dem Qibla-Pfeil aus, um die Kaaba zu finden.",
        "qibla_angle" to "Qibla-Winkel",
        "daily_azkar" to "Tägliche Azkar",
        "repeat" to "Wiederholen",
        "share" to "Teilen",
        "favorite" to "Favorit",
        "khatmah_planner" to "Khatmah-Planer",
        "pages_read" to "Gelesene Seiten",
        "remaining" to "Verbleibend",
        "daily_target" to "Tägliches Ziel",
        "add_pages" to "+5 Seiten",
        "add_juz" to "+1 Juz' (20 S.)",
        "unlocked" to "Freigeschaltet",
        "locked" to "Gesperrt",
        "bronze_badge" to "Bronze-Gelehrter",
        "silver_badge" to "Silber-Huffaz",
        "gold_badge" to "Goldener Noor",
        "start_khatmah" to "Khatmah starten",
        "reach_50" to "50% erreichen",
        "complete_quran" to "Koran beenden",
        "create_new_khatmah" to "Neuen Khatmah-Plan erstellen",
        "title" to "Plan-Titel",
        "finish_goal" to "Ziel (Tage)",
        "daily_reading_target" to "Tägliches Leseziel (Minuten)",
        "initialize_khatmah" to "Plan starten",
        "praise_allah" to "Preise Allah",
        "memorization_quiz" to "Auswendiglern-Quiz",
        "streak" to "Serie",
        "verify_answer" to "Antwort überprüfen",
        "next_question" to "Nächste Frage",
        "islamic_duas" to "Islamische Bittgebete",
        "holy_quran" to "Heiliger Koran",
        "search_surah" to "Sure oder englische Bedeutung suchen...",
        "surahs" to "Suren",
        "bookmarks" to "Lesezeichen",
        "no_bookmarks" to "Noch keine Lesezeichen vorhanden.",
        "reciting" to "Rezitator",
        "word_meanings" to "Wortbedeutungen (Zum Einklappen tippen)",
        "tafsir_title" to "Tafsir Al-Muntakhab",
        "play_audio" to "Audio abspielen",
        "stop" to "Stopp",
        "copied" to "Vers kopiert!",
        "morning" to "Morgen",
        "evening" to "Abend",
        "sleep" to "Schlaf",
        "travel" to "Reise",
        "next_prayer" to "Nächstes",
        "utc_live" to "UTC LIVE",
        "ai_scholar" to "Noor Al-Koran AI",
        "chat_placeholder" to "Fragen Sie nach Koranbedeutungen, Tafsir oder islamischer Führung...",
        "ai_thinking" to "Noor AI denkt nach...",
        "clear_chat" to "Chat löschen",
        "select_reciter" to "Rezitator auswählen",
        "change_reciter" to "Stimme ändern",
        "reciter_mishary" to "Mishary Rashid Alafasy",
        "reciter_abdul_basit" to "Abdul Basit Abdus Samad",
        "reciter_minshawi" to "Mohamed Siddiq El-Minshawi",
        "reciter_shuraim" to "Saud Al-Shuraim",
        "reciter_sudais" to "Abdul Rahman Al-Sudais",
        "reciter_yasser_al_dosari" to "Yasser Al-Dosari",
        "reciter_islam_sobhi" to "Islam Sobhi",
        "daylight_saving_time" to "Sommerzeit (+1h)",
        "prayer_approaching_alert" to "Gebetswarnung (15 Min)",
        "tasbeeh_sound" to "Tasbih-Klickton",
        "tasbeeh_vibration" to "Tasbih-Vibration",
        "download" to "Herunterladen",
        "downloaded" to "Heruntergeladen",
        "downloading" to "Herunterladen...",
        "delete_audio" to "Offline-Audio löschen",
        "live_radio" to "Live-Radio",
        "live_radio_subtitle" to "Direkte Live-Koranübertragungen",
        "choose_radio" to "Live-Übertragung wählen",
        "radio_cairo" to "Koran Radio Kairo",
        "radio_saudi" to "Koran Radio Saudi-Arabien",
        "radio_alafasy" to "Mishary Alafasy Live",
        "radio_basit" to "Abdul Basit Live",
        "radio_minshawi" to "El-Minshawi Live",
        "radio_yasser" to "Yasser Al-Dosari Live",
        "radio_maher" to "Maher Al-Muaiqly Live",
        "radio_ajmy" to "Ahmad Al-Ajmy Live",
        "radio_ghamdi" to "Saad Al-Ghamdi Live",
        "radio_shuraim" to "Saud Al-Shuraim Live",
        "radio_sudais" to "Al-Sudais Live",
        "live_broadcasting" to "LIVE-ÜBERTRAGUNG",
        "now_playing_radio" to "Aktuelle Live-Übertragung",
        "downloads" to "Downloads",
        "downloads_subtitle" to "Heruntergeladene Koran- & Adhan-Audiodateien",
        "all_downloads" to "Meine Downloads",
        "quran_downloads" to "Koran-Audio",
        "adhan_downloads" to "Adhan-Audio",
        "no_downloads" to "Noch keine heruntergeladenen Audiodateien",
        "battery_card_title" to "Hintergrundstabilität",
        "battery_card_desc" to "Nehmen Sie die App von der Akku-Optimierung aus, um genaue Adhan-Warnungen zu erhalten",
        "battery_card_btn" to "Von der Optimierung ausnehmen"
    )

    private val hindiTranslations = mapOf(
        "home" to "मुख्य पृष्ठ",
        "welcome" to "अस्सलाम अलैकुम,",
        "quick_services" to "त्वरित सेवाएं",
        "daily_verse" to "दैनिक कुरान आयत",
        "read_tafsir" to "तफसीर पढ़ें",
        "continue_reading" to "पढ़ना जारी रखें",
        "quran_listening" to "कुरान सुनना",
        "daily_hadith" to "दैनिक हदीस",
        "quran" to "कुरान",
        "prayer_times" to "प्रार्थना का समय",
        "qibla" to "किबला",
        "azkar" to "अज़कार",
        "audio_quran" to "ऑडियो कुरान",
        "khatmah" to "खातमा",
        "quiz" to "प्रश्नोत्तरी",
        "duas" to "दुआएं",
        "tasbeeh" to "तस्बीह",
        "settings" to "सेटिंग्स",
        "save" to "सहेजें",
        "edit_name" to "नाम बदलें",
        "settings_options" to "विकल्प और सेटिंग्स",
        "dark_mode" to "ओब्सीडियन एमराल्ड डार्क मोड",
        "quran_font_style" to "कुरान अरबी फ़ॉन्ट शैली",
        "quran_text_size" to "कुरान पढ़ने का आकार",
        "prayer_calc_method" to "प्रार्थना गणना विधि",
        "app_language" to "ऐप की भाषा",
        "choose_language" to "भाषा चुनें",
        "back" to "पीछे",
        "compass" to "किबला कम्पास",
        "align_phone" to "काबा खोजने के लिए अपने फोन को किबला तीर की दिशा में रखें।",
        "qibla_angle" to "किबला कोण",
        "daily_azkar" to "दैनिक अज़कार",
        "repeat" to "दोहराएं",
        "share" to "साझा करें",
        "favorite" to "पसंदीदा",
        "khatmah_planner" to "खातमा योजनाकार",
        "pages_read" to "पढ़े गए पृष्ठ",
        "remaining" to "शेष",
        "daily_target" to "दैनिक लक्ष्य",
        "add_pages" to "+5 पृष्ठ",
        "add_juz" to "+1 जुज़ (20 पृष्ठ)",
        "unlocked" to "अनलॉक किया गया",
        "locked" to "लॉक किया गया",
        "bronze_badge" to "कांस्य विद्वान",
        "silver_badge" to "रजत हुफ़ाज़",
        "gold_badge" to "स्वर्ण नूर",
        "start_khatmah" to "खातमा शुरू करें",
        "reach_50" to "50% तक पहुँचें",
        "complete_quran" to "कुरान पूरा करें",
        "create_new_khatmah" to "नया खातमा बनाएं",
        "title" to "योजना का शीर्षक",
        "finish_goal" to "समाप्ति लक्ष्य (दिन)",
        "daily_reading_target" to "दैनिक पढ़ने का लक्ष्य (मिनट)",
        "initialize_khatmah" to "योजना शुरू करें",
        "praise_allah" to "अल्लाह की प्रशंसा करें",
        "memorization_quiz" to "याद रखने की प्रश्नोत्तरी",
        "streak" to "सिलसिला",
        "verify_answer" to "उत्तर सत्यापित करें",
        "next_question" to "अगला प्रश्न",
        "islamic_duas" to "इस्लामिक दुआएं",
        "holy_quran" to "पवित्र कुरान",
        "search_surah" to "सूरा या अर्थ खोजें...",
        "surahs" to "सूरा",
        "bookmarks" to "बुकमार्क",
        "no_bookmarks" to "कोई बुकमार्क नहीं।",
        "reciting" to "पाठक",
        "word_meanings" to "शब्द अर्थ (छिपाने के लिए टैप करें)",
        "tafsir_title" to "तफसीर अल-मुंतखाब",
        "play_audio" to "ऑडियो चलाएं",
        "stop" to "रोकें",
        "copied" to "आयत कॉपी की गई!",
        "morning" to "सुबह",
        "evening" to "शाम",
        "sleep" to "सोते समय",
        "travel" to "यात्रा",
        "next_prayer" to "अगला",
        "utc_live" to "यूटीसी लाइव",
        "ai_scholar" to "नूर अल-कुरान एआई",
        "chat_placeholder" to "कुरान के अर्थ, तफसीर या इस्लामिक मार्गदर्शन के बारे में पूछें...",
        "ai_thinking" to "नूर एआई सोच रहा है...",
        "clear_chat" to "चैट साफ़ करें",
        "select_reciter" to "पाठक चुनें",
        "change_reciter" to "आवाज बदलें",
        "reciter_mishary" to "मिशारी राशिद अलाफसी",
        "reciter_abdul_basit" to "अब्दुल बासित अब्दुस समद",
        "reciter_minshawi" to "मोहम्मद सिद्दीक अल-मिंशावी",
        "reciter_shuraim" to "सऊद अल-शुरैम",
        "reciter_sudais" to "अब्दुल रहमान अल-सुदैस",
        "reciter_yasser_al_dosari" to "यासिर अल-दोसारी",
        "reciter_islam_sobhi" to "इस्लाम सोभी",
        "daylight_saving_time" to "डेलाइट सेविंग टाइम (+1 घंटा)",
        "prayer_approaching_alert" to "प्रार्थना चेतावनी (15 मिनट)",
        "tasbeeh_sound" to "तस्बीह क्लिक ध्वनि",
        "tasbeeh_vibration" to "तस्बीह कंपन",
        "download" to "डाउनलोड करें",
        "downloaded" to "डाउनलोड किया गया",
        "downloading" to "डाउनलोड हो रहा है...",
        "delete_audio" to "ऑफ़लाइन ऑडियो हटाएं",
        "live_radio" to "लाइव रेडियो",
        "live_radio_subtitle" to "सीधा लाइव कुरान प्रसारण",
        "choose_radio" to "लाइ复播...",
        "radio_cairo" to "कुरान रेडियो काहिरा",
        "radio_saudi" to "कुरान रेडियो सऊदी",
        "radio_alafasy" to "मिशारी अलाफसी लाइव",
        "radio_basit" to "अब्दुल बासित लाइव",
        "radio_minshawi" to "अल-मिंशावी लाइव",
        "radio_yasser" to "यासिर अल-दोसारी लाइव",
        "radio_maher" to "माहेर अल-मुइक्ली लाइव",
        "radio_ajmy" to "अहमद अल-अजमी लाइव",
        "radio_ghamdi" to "साद अल-गामदी लाइव",
        "radio_shuraim" to "सऊद अल-शुरैम लाइव",
        "radio_sudais" to "अल-सुदैस लाइव",
        "live_broadcasting" to "लाइव प्रसारण",
        "now_playing_radio" to "अभी चल रहा लाइव रेडियो",
        "downloads" to "डाउनलोड",
        "downloads_subtitle" to "डाउनलोड किए गए कुरान और अज़ान ऑडियो",
        "all_downloads" to "मेरे डाउनलोड",
        "quran_downloads" to "कुरान ऑडियो",
        "adhan_downloads" to "अज़ान ऑडियो",
        "no_downloads" to "कोई डाउनलोड की गई ऑडियो फ़ाइल नहीं है",
        "battery_card_title" to "पृष्ठभूमि स्थिरता",
        "battery_card_desc" to "सटीक अज़ान अलर्ट के लिए ऐप को बैटरी प्रतिबंध से मुक्त करें",
        "battery_card_btn" to "प्रतिबंध से मुक्त करें"
    )

    private val chineseTranslations = mapOf(
        "home" to "首页",
        "welcome" to "安塞俩目阿莱库姆，",
        "quick_services" to "快捷服务",
        "daily_verse" to "每日古兰经金句",
        "read_tafsir" to "阅读经注 (Tafsir)",
        "continue_reading" to "继续阅读",
        "quran_listening" to "古兰经聆听",
        "daily_hadith" to "每日圣训",
        "quran" to "古兰经",
        "prayer_times" to "礼拜时间",
        "qibla" to "朝向 (Qibla)",
        "azkar" to "赞念 (Azkar)",
        "audio_quran" to "音频古兰经",
        "khatmah" to "古兰经诵读计划 (Khatmah)",
        "quiz" to "测验",
        "duas" to "祈祷词 (Duas)",
        "tasbeeh" to "电子念珠 (Tasbeeh)",
        "settings" to "设置",
        "save" to "保存",
        "edit_name" to "修改名字",
        "settings_options" to "设置与选项",
        "dark_mode" to "翡翠暗黑模式",
        "quran_font_style" to "古兰经阿拉伯语字体",
        "quran_text_size" to "古兰经阅读字体大小",
        "prayer_calc_method" to "礼拜时间计算方法",
        "app_language" to "应用语言",
        "choose_language" to "选择语言",
        "back" to "返回",
        "compass" to "朝向指南针",
        "align_phone" to "将手机对准朝向箭头以寻找克尔白。",
        "qibla_angle" to "朝向角度",
        "daily_azkar" to "每日赞念",
        "repeat" to "重复",
        "share" to "分享",
        "favorite" to "收藏",
        "khatmah_planner" to "诵读计划制定器",
        "pages_read" to "已读页数",
        "remaining" to "剩余页数",
        "daily_target" to "每日目标",
        "add_pages" to "+5 页",
        "add_juz" to "+1 卷 (20页)",
        "unlocked" to "已解锁",
        "locked" to "已锁定",
        "bronze_badge" to "铜牌学者",
        "silver_badge" to "银牌哈菲兹",
        "gold_badge" to "金牌真主之光",
        "start_khatmah" to "开始计划",
        "reach_50" to "完成 50%",
        "complete_quran" to "完成通读",
        "create_new_khatmah" to "创建新诵读计划",
        "title" to "计划标题",
        "finish_goal" to "完成目标（天数）",
        "daily_reading_target" to "每日阅读目标（分钟）",
        "initialize_khatmah" to "初始化计划",
        "praise_allah" to "赞美真主",
        "memorization_quiz" to "背诵测验",
        "streak" to "连续天数",
        "verify_answer" to "验证答案",
        "next_question" to "下一题",
        "islamic_duas" to "伊斯兰祈祷词",
        "holy_quran" to "神圣古兰经",
        "search_surah" to "搜索苏拉或含义...",
        "surahs" to "苏拉 (章)",
        "bookmarks" to "书签",
        "no_bookmarks" to "暂无书签。",
        "reciting" to "诵读家",
        "word_meanings" to "单词含义（点击折叠）",
        "tafsir_title" to "经注 Al-Muntakhab",
        "play_audio" to "播放音频",
        "stop" to "停止",
        "copied" to "已复制经文！",
        "morning" to "晨间赞念",
        "evening" to "晚间赞念",
        "sleep" to "临睡赞念",
        "travel" to "旅行赞念",
        "next_prayer" to "下一次礼拜",
        "utc_live" to "UTC 直播",
        "ai_scholar" to "诺尔古兰经 AI 导师",
        "chat_placeholder" to "咨询古兰经含义、经注或伊斯兰指引...",
        "ai_thinking" to "诺尔 AI 正在思考...",
        "clear_chat" to "清空对话",
        "select_reciter" to "选择诵读家",
        "change_reciter" to "更改声音",
        "reciter_mishary" to "米沙里·拉希德",
        "reciter_abdul_basit" to "阿卜杜勒·巴西特",
        "reciter_minshawi" to "民沙维",
        "reciter_shuraim" to "舒莱姆",
        "reciter_sudais" to "苏代斯",
        "reciter_yasser_al_dosari" to "亚西尔·杜萨里",
        "reciter_islam_sobhi" to "伊斯兰·索比",
        "daylight_saving_time" to "夏令时 (+1小时)",
        "prayer_approaching_alert" to "礼拜临近提醒 (15分钟)",
        "tasbeeh_sound" to "电子念珠按键音",
        "tasbeeh_vibration" to "电子念珠振动",
        "download" to "下载",
        "downloaded" to "已下载",
        "downloading" to "正在下载...",
        "delete_audio" to "删除离线音频",
        "live_radio" to "网络电台直播",
        "live_radio_subtitle" to "直通古兰经直播频道",
        "choose_radio" to "选择电台",
        "radio_cairo" to "开罗古兰经电台",
        "radio_saudi" to "沙特古兰经电台",
        "radio_alafasy" to "米沙里电台直播",
        "radio_basit" to "阿卜杜勒·巴西特直播",
        "radio_minshawi" to "民沙维直播",
        "radio_yasser" to "亚西尔·杜萨里直播",
        "radio_maher" to "马赫尔直播",
        "radio_ajmy" to "阿杰米直播",
        "radio_ghamdi" to "甘迪直播",
        "radio_shuraim" to "舒莱姆直播",
        "radio_sudais" to "苏代斯直播",
        "live_broadcasting" to "实时直播",
        "now_playing_radio" to "当前播放电台",
        "downloads" to "下载管理",
        "downloads_subtitle" to "已下载的音频文件",
        "all_downloads" to "我的下载",
        "quran_downloads" to "古兰经音频",
        "adhan_downloads" to "宣礼 (Adhan) 音频",
        "no_downloads" to "暂无下载的音频文件",
        "battery_card_title" to "后台运行稳定性",
        "battery_card_desc" to "请免除应用电池限制，以确保准时接收宣礼提醒",
        "battery_card_btn" to "免除限制"
    )

    private val spanishTranslations = mapOf(
        "home" to "Inicio",
        "welcome" to "Assalamu Alaykum,",
        "quick_services" to "Servicios Rápidos",
        "daily_verse" to "Versículo Diario del Corán",
        "read_tafsir" to "Leer Tafsir",
        "continue_reading" to "Continuar Leyendo",
        "quran_listening" to "Escuchar el Corán",
        "daily_hadith" to "Hadiz Diario",
        "quran" to "Corán",
        "prayer_times" to "Horarios de Oración",
        "qibla" to "Qibla",
        "azkar" to "Azkar",
        "audio_quran" to "Corán en Audio",
        "khatmah" to "Khatmah",
        "quiz" to "Cuestionario",
        "duas" to "Súplicas (Duas)",
        "tasbeeh" to "Tasbih",
        "settings" to "Ajustes",
        "save" to "Guardar",
        "edit_name" to "Editar Nombre",
        "settings_options" to "Ajustes y Opciones",
        "dark_mode" to "Modo Oscuro Esmeralda",
        "quran_font_style" to "Estilo de Fuente Árabe Coránica",
        "quran_text_size" to "Tamaño de Texto del Corán",
        "prayer_calc_method" to "Método de Cálculo de Oración",
        "app_language" to "Idioma de la Aplicación",
        "choose_language" to "Elegir Idioma",
        "back" to "Atrás",
        "compass" to "Brújula de Qibla",
        "align_phone" to "Alinee su teléfono con la flecha para encontrar la Kaaba.",
        "qibla_angle" to "Ángulo de Qibla",
        "daily_azkar" to "Azkar Diario",
        "repeat" to "Repetir",
        "share" to "Compartir",
        "favorite" to "Favorito",
        "khatmah_planner" to "Planificador de Khatmah",
        "pages_read" to "Páginas Leídas",
        "remaining" to "Restantes",
        "daily_target" to "Objetivo Diario",
        "add_pages" to "+5 Páginas",
        "add_juz" to "+1 Juz' (20 pág.)",
        "unlocked" to "Desbloqueado",
        "locked" to "Bloqueado",
        "bronze_badge" to "Erudito de Bronce",
        "silver_badge" to "Huffaz de Plata",
        "gold_badge" to "Noor Dorado",
        "start_khatmah" to "Iniciar Khatmah",
        "reach_50" to "Alcanzar 50%",
        "complete_quran" to "Completar Corán",
        "create_new_khatmah" to "Crear Plan de Khatmah",
        "title" to "Título del Plan",
        "finish_goal" to "Meta (Días)",
        "daily_reading_target" to "Meta de Lectura Diaria (Minutos)",
        "initialize_khatmah" to "Iniciar Plan",
        "praise_allah" to "Alabar a Allah",
        "memorization_quiz" to "Cuestionario de Memorización",
        "streak" to "Racha",
        "verify_answer" to "Verificar Respuesta",
        "next_question" to "Siguiente Pregunta",
        "islamic_duas" to "Súplicas Islámicas",
        "holy_quran" to "Santo Corán",
        "search_surah" to "Buscar Sura o significado...",
        "surahs" to "Suras",
        "bookmarks" to "Marcadores",
        "no_bookmarks" to "No hay marcadores aún.",
        "reciting" to "Recitador",
        "word_meanings" to "Significado de Palabras (Tocar para contraer)",
        "tafsir_title" to "Tafsir Al-Muntakhab",
        "play_audio" to "Reproducir Audio",
        "stop" to "Detener",
        "copied" to "¡Versículo copiado!",
        "morning" to "Mañana",
        "evening" to "Tarde",
        "sleep" to "Dormir",
        "travel" to "Viaje",
        "next_prayer" to "Siguiente Oración",
        "utc_live" to "UTC EN VIVO",
        "ai_scholar" to "Noor Al-Quran AI",
        "chat_placeholder" to "Pregunte sobre significados del Corán, Tafsir o guía islámica...",
        "ai_thinking" to "Noor AI está pensando...",
        "clear_chat" to "Limpiar Chat",
        "select_reciter" to "Seleccionar Recitador",
        "change_reciter" to "Cambiar Voz",
        "reciter_mishary" to "Mishary Rashid Alafasy",
        "reciter_abdul_basit" to "Abdul Basit Abdus Samad",
        "reciter_minshawi" to "Mohamed Siddiq El-Minshawi",
        "reciter_shuraim" to "Saud Al-Shuraim",
        "reciter_sudais" to "Abdul Rahman Al-Sudais",
        "reciter_yasser_al_dosari" to "Yasser Al-Dosari",
        "reciter_islam_sobhi" to "Islam Sobhi",
        "daylight_saving_time" to "Horario de Verano (+1h)",
        "prayer_approaching_alert" to "Alerta de Oración (15m)",
        "tasbeeh_sound" to "Sonido de Clic de Tasbih",
        "tasbeeh_vibration" to "Vibración de Tasbih",
        "download" to "Descargar",
        "downloaded" to "Descargado",
        "downloading" to "Descargando...",
        "delete_audio" to "Eliminar Audio Offline",
        "live_radio" to "Radio en Vivo",
        "live_radio_subtitle" to "Transmisiones Directas del Corán",
        "choose_radio" to "Elegir Transmisión",
        "radio_cairo" to "Radio del Corán de El Cairo",
        "radio_saudi" to "Radio del Corán de Arabia Saudita",
        "radio_alafasy" to "Mishary Alafasy en Vivo",
        "radio_basit" to "Abdul Basit en Vivo",
        "radio_minshawi" to "El-Minshawi en Vivo",
        "radio_yasser" to "Yasser Al-Dosari en Vivo",
        "radio_maher" to "Maher Al-Muaiqly en Vivo",
        "radio_ajmy" to "Ahmad Al-Ajmy en Vivo",
        "radio_ghamdi" to "Saad Al-Ghamdi en Vivo",
        "radio_shuraim" to "Saud Al-Shuraim en Vivo",
        "radio_sudais" to "Al-Sudais en Vivo",
        "live_broadcasting" to "TRANSMISIÓN EN VIVO",
        "now_playing_radio" to "Reproduciendo en Vivo",
        "downloads" to "Descargas",
        "downloads_subtitle" to "Audios descargados de Corán y Adhan",
        "all_downloads" to "Mis Descargas",
        "quran_downloads" to "Audio del Corán",
        "adhan_downloads" to "Audio de Adhan",
        "no_downloads" to "No hay audios descargados aún",
        "battery_card_title" to "Estabilidad en Segundo Plano",
        "battery_card_desc" to "Exima la app de restricciones de batería para recibir alertas de Adhan a tiempo",
        "battery_card_btn" to "Eximir de Optimización"
    )

    private val frenchTranslations = mapOf(
        "home" to "Accueil",
        "welcome" to "Assalamu Alaykum,",
        "quick_services" to "Services Rapides",
        "daily_verse" to "Verset Quotidien du Coran",
        "read_tafsir" to "Lire le Tafsir",
        "continue_reading" to "Continuer la Lecture",
        "quran_listening" to "Écouter le Coran",
        "daily_hadith" to "Hadith Quotidien",
        "quran" to "Coran",
        "prayer_times" to "Heures de Prière",
        "qibla" to "Qibla",
        "azkar" to "Azkar",
        "audio_quran" to "Coran Audio",
        "khatmah" to "Khatmah",
        "quiz" to "Quiz",
        "duas" to "Invocations (Duas)",
        "tasbeeh" to "Tasbih",
        "settings" to "Paramètres",
        "save" to "Enregistrer",
        "edit_name" to "Modifier le Nom",
        "settings_options" to "Options & Paramètres",
        "dark_mode" to "Mode Sombre Émeraude",
        "quran_font_style" to "Style de Police Arabe Coranique",
        "quran_text_size" to "Taille de Texte du Coran",
        "prayer_calc_method" to "Méthode de Calcul des Prières",
        "app_language" to "Langue de l'App",
        "choose_language" to "Choisir la Langue",
        "back" to "Retour",
        "compass" to "Boussole Qibla",
        "align_phone" to "Alignez votre téléphone avec la flèche pour trouver la Kaaba.",
        "qibla_angle" to "Angle de la Qibla",
        "daily_azkar" to "Azkar Quotidien",
        "repeat" to "Répéter",
        "share" to "Partager",
        "favorite" to "Favori",
        "khatmah_planner" to "Planificateur de Khatmah",
        "pages_read" to "Pages Lu",
        "remaining" to "Restantes",
        "daily_target" to "Cible Quotidienne",
        "add_pages" to "+5 Pages",
        "add_juz" to "+1 Juz' (20 pág.)",
        "unlocked" to "Déverrouillé",
        "locked" to "Verrouillé",
        "bronze_badge" to "Érudit de Bronze",
        "silver_badge" to "Huffaz d'Argent",
        "gold_badge" to "Noor d'Or",
        "start_khatmah" to "Démarrer Khatmah",
        "reach_50" to "Atteindre 50%",
        "complete_quran" to "Compléter le Coran",
        "create_new_khatmah" to "Créer un Plan Khatmah",
        "title" to "Titre du Plan",
        "finish_goal" to "Objectif (Jours)",
        "daily_reading_target" to "Cible de Lecture Quotidienne (Minutes)",
        "initialize_khatmah" to "Démarrer le Plan",
        "praise_allah" to "Glorifier Allah",
        "memorization_quiz" to "Quiz de Mémorisation",
        "streak" to "Série",
        "verify_answer" to "Vérifier la Réponse",
        "next_question" to "Question Suivante",
        "islamic_duas" to "Invocations Islamiques",
        "holy_quran" to "Saint Coran",
        "search_surah" to "Rechercher une Sourate...",
        "surahs" to "Sourates",
        "bookmarks" to "Signets",
        "no_bookmarks" to "Aucun signet pour le moment.",
        "reciting" to "Récitateur",
        "word_meanings" to "Sens des Mots (Appuyez pour masquer)",
        "tafsir_title" to "Tafsir Al-Muntakhab",
        "play_audio" to "Lire l'Audio",
        "stop" to "Arrêter",
        "copied" to "Verset copié !",
        "morning" to "Matin",
        "evening" to "Soir",
        "sleep" to "Sommeil",
        "travel" to "Voyage",
        "next_prayer" to "Prière Suivante",
        "utc_live" to "UTC EN DIRECT",
        "ai_scholar" to "Noor Al-Quran AI",
        "chat_placeholder" to "Posez des questions sur le Coran, Tafsir ou la guidance...",
        "ai_thinking" to "Noor AI réfléchit...",
        "clear_chat" to "Effacer la Conversation",
        "select_reciter" to "Choisir un Récitateur",
        "change_reciter" to "Modifier la Voix",
        "reciter_mishary" to "Mishary Rashid Alafasy",
        "reciter_abdul_basit" to "Abdul Basit Abdus Samad",
        "reciter_minshawi" to "Mohamed Siddiq El-Minshawi",
        "reciter_shuraim" to "Saud Al-Shuraim",
        "reciter_sudais" to "Abdul Rahman Al-Sudais",
        "reciter_yasser_al_dosari" to "Yasser Al-Dosari",
        "reciter_islam_sobhi" to "Islam Sobhi",
        "daylight_saving_time" to "Heure d'Été (+1h)",
        "prayer_approaching_alert" to "Alerte de Prière Proche (15m)",
        "tasbeeh_sound" to "Clic Sonore du Tasbih",
        "tasbeeh_vibration" to "Vibration du Tasbih",
        "download" to "Télécharger",
        "downloaded" to "Téléchargé",
        "downloading" to "Téléchargement...",
        "delete_audio" to "Supprimer l'Audio Hors-ligne",
        "live_radio" to "Radio en Direct",
        "live_radio_subtitle" to "Radios Coraniques en Direct",
        "choose_radio" to "Choisir une Station",
        "radio_cairo" to "Radio du Coran du Caire",
        "radio_saudi" to "Radio du Coran d'Arabie Saoudite",
        "radio_alafasy" to "Mishary Alafasy en Direct",
        "radio_basit" to "Abdul Basit en Direct",
        "radio_minshawi" to "El-Minshawi en Direct",
        "radio_yasser" to "Yasser Al-Dosari en Direct",
        "radio_maher" to "Maher Al-Muaiqly en Direct",
        "radio_ajmy" to "Ahmad Al-Ajmy en Direct",
        "radio_ghamdi" to "Saad Al-Ghamdi en Direct",
        "radio_shuraim" to "Saud Al-Shuraim en Direct",
        "radio_sudais" to "Al-Sudais en Direct",
        "live_broadcasting" to "DIFFUSION EN DIRECT",
        "now_playing_radio" to "En cours de diffusion",
        "downloads" to "Téléchargements",
        "downloads_subtitle" to "Fichiers audio de Coran et d'Adhan téléchargés",
        "all_downloads" to "Mes Téléchargements",
        "quran_downloads" to "Audio du Coran",
        "adhan_downloads" to "Audio d'Adhan",
        "no_downloads" to "Aucun audio téléchargé pour le moment",
        "battery_card_title" to "Stabilité en Arrière-plan",
        "battery_card_desc" to "Excluez l'application de l'optimisation de batterie pour les alertes d'Adhan",
        "battery_card_btn" to "Exclure de l'Optimisation"
    )
}
